language: ruby
env: CUCUMBER_FORMAT=progress
bundler_args: --without extras
script: "bundle exec ruby -w -I./spec -r./spec/capture_warnings -rspec_helper -S rspec ./spec/vcr_spec.rb ./spec/quality_spec.rb ./spec/vcr/deprecations_spec.rb ./spec/vcr/test_frameworks/rspec_spec.rb ./spec/vcr/test_frameworks/cucumber_spec.rb ./spec/vcr/middleware/faraday_spec.rb ./spec/vcr/middleware/rack_spec.rb ./spec/vcr/extensions/net_http_response_spec.rb ./spec/vcr/structs_spec.rb ./spec/vcr/request_matcher_registry_spec.rb ./spec/vcr/cassette_spec.rb ./spec/vcr/library_hooks_spec.rb ./spec/vcr/cassette/migrator_spec.rb ./spec/vcr/cassette/http_interaction_list_spec.rb ./spec/vcr/cassette/serializers_spec.rb ./spec/vcr/cassette/persisters_spec.rb ./spec/vcr/cassette/erb_renderer_spec.rb ./spec/vcr/cassette/persisters/file_system_spec.rb ./spec/vcr/configuration_spec.rb ./spec/vcr/library_hooks/faraday_spec.rb ./spec/vcr/library_hooks/typhoeus_spec.rb ./spec/vcr/library_hooks/excon_spec.rb ./spec/vcr/library_hooks/fakeweb_spec.rb ./spec/vcr/library_hooks/webmock_spec.rb ./spec/vcr/errors_spec.rb ./spec/vcr/version_spec.rb ./spec/vcr/request_ignorer_spec.rb ./spec/vcr/util/version_checker_spec.rb ./spec/vcr/util/hooks_spec.rb ./spec/vcr/util/internet_connection_spec.rb --format progress --backtrace"
rvm:
  - 1.9.2
  - 1.9.3
branches:
  only:
    - master
    - 1-x-stable
    - travis-testing
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode

