language: ruby
env: CUCUMBER_FORMAT=progress
bundler_args: --without extras
script: "bundle exec rake spec --trace"
rvm:
  - 1.9.2
branches:
  only:
    - master
    - 1-x-stable
    - travis-testing
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode

